### ISSUE TITLE
Love the idea -  Some suggestions

### ISSUE THREAD

**Issue by imranique** [EmanuelBender/HEX_POD#1]
Hi,

I was looking for the best Air Quality Monitor, and I stumbled upon your project. Here are some suggestions if you are interested.

1. Can you present in a clearer way (more description, less abbreviation) what is currently measured?
2. Have a look at [this project](https://github.com/MarcFinns/AtmoScan) for ideas on more sensors to add, notably radon, noise and HCHO.
3. I know the goal is to have a portable device, but it would be great to also consider a static device to install in a room for Home Assistant or commercial settings that includes Power over Ethernet (POE) for both power and data, and perhaps an option without a screen (but with a port for setting it up or debugging)...

Best of luck; you are clearly talented.

Cheers

**Comment by EmanuelBender** [comment]
Hey thanks so much for the feedback and i agree with you!

1. The documentation and explanation is not great yet. This has two reasons:
- i am not completely done yet, but 
- i am also really bad at this, when i write too much i think its too convoluted and complicated and if i summarise it down it doesn't say much...

2. Ah nice this is a great one, haven't seen it before. I already did extensive research into what sensors to use etc and fortunately sensors have evolved quite a bit since the CS811 and HDC1080 (i had these in at some point)
Also radiation and PM2.5 would be cool to measure, but i want it to be compact and these just don't fit physically. Also i think with ML and sensor fusion they might not be necessary, plus i want to focus on Air compounds first. That being said, the included BME688 is ready to be used for AI stuff and could in theory detect a whole range of things, working on that right now.

This is my current **wishlist** for sensors and features that don't fit or will be implemented later:
PM1.0 / PM2.5 Sensor
! [Smart NanoTubes sensor](https://smart-nanotubes.com/) 
Oxygen (O2) Sensor
Ozone (O3) Sensor
Ethanol, Alcohol sensors
Water Quality sensor
On-device AI/ML training
Emergency Radio communication (FM, LoRa, UWB)
Emergency Satellite communication, tracking (GSM+)
Passive power generation
Laser Range finder
24bit Sterero Audio Recorder & Spectrum Analyzer
[Light Spectrometer](https://www.hamamatsu.com/eu/en/product/optical-sensors/spectrometers/mini-spectrometer/C12666MA.html)
Human & Animal presence detection
[ENS161 - Multi Gas Sensor](https://www.sciosense.com/products/environmental-sensors/ens16x-digital-metal-oxide-multi-gas-sensor/)

3. Yep all good thoughts! Below is a similar design version that could act as a single sensor point for a sensor mesh network with low energy screen for example. POE and making it convenient to integrate is definitely on the priority list, but making it work comes first.

![PUCK 2](https://github.com/EmanuelBender/HEX_POD/assets/46021872/2b1909d1-e4a5-454e-8ce8-81046070d3c6)


thanks!

**Comment by imranique** [comment]
Thanks for the response!

1. One trick I was told is to ask someone who knows nothing about this (the famous mom's example) and see if they understand. If not, you add a little until it works. It's a challenge, that's for sure.
2. Cool that you are already thinking of new sensors. Of course, as someone with a room sensor goal, some of them are not really useful, but some of them are incredibly great ideas and unique.
3. That is a great design, wow. Again, for me, I don't really see the point of another screen in a room, especially since those will be integrated into other platforms with their own dashboards. I feel like a room sensor should be as discreet as possible, especially since it's not like a thermostat where user interactions need to happen. This said, such a design has the advantage of being modular for the needs of the end user. Also, I assume removing some parts like the screen and controls has the added benefit of lower cost and greater flexibility with the design. I guess my point is that the design philosophy of a standalone device is really not the same as a room sensor that will be tied to another ecosystem.

I really look forward to deploying some of them in my home, and I think a lot of commercial settings would be interested in POE and MQTT.

**Comment by EmanuelBender** [comment]
Definitely! 
MQTT, HomeSpan (HomeKit), Grafana integration and similar are all great things i want to try to implement if possible.
A no screen version could definitely work as well, and is pretty easy to derivate from the main version. Modularity was also part of the plan already. I just don't have the time and experience to implement all these things quickly, but i'm learning and it's fun. 
thanks for the interest and suggestions!
